#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Get SS official libs

on:
  workflow_dispatch:
    inputs:
      re_version:
        description: "Regular version"
        default: "9.2"
        type: string
      patch_list:
        description: "patch list"
        # default: "bin/* lib/* sbin/*"
        default: ""
        type: string

jobs:
  official:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init Env
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Get official libs
        run: |
          RE_VERSION="${{ inputs.re_version }}" PATCH_LIST="${{ inputs.patch_list }}" official/official.sh

      - name: Check and Push
        run: |
          git pull
          status=$(git status -s | grep -E 'official' | awk '{printf " %s", $2}')
          if [ -n "${status}" ]; then
            git add ${status}
            git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
            git push -f
          fi
